"""One-time migration: fix Chinese canonical names and IDs in trend_terms.json.

Generated by today's pipeline (2026-07-10) which ran old code without
_ensure_english_canonical() enforcement.

Usage: python scripts/fix_chinese_canonicals.py [--dry-run]
"""
import json
import re
import sys
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

TREND_TERMS_PATH = ROOT / "tracking" / "trend_terms.json"
CONTENT_DIR = ROOT / "content" / "trends"


def _has_chinese(text: str) -> bool:
    """Check if text contains Chinese characters."""
    return any('一' <= c <= '鿿' or '㐀' <= c <= '䶿' for c in text)


def _make_slug_id(canonical: str) -> str:
    """Generate URL-safe English slug from canonical name."""
    import hashlib

    if not _has_chinese(canonical):
        slug = re.sub(r'[^\w\s\-.]', '', canonical.lower()).strip()
        slug = re.sub(r'[-\s]+', '-', slug)[:50]
        return f"trend-{slug}"

    ascii_parts = re.findall(r'[A-Za-z0-9]+(?:[.\-+/][A-Za-z0-9]+)*', canonical)
    if ascii_parts:
        meaningful = [p for p in ascii_parts if len(p) >= 2 or p.isdigit()]
        if meaningful:
            slug = '-'.join(p.lower() for p in meaningful)[:50]
            return f"trend-{slug}"

    h = hashlib.md5(canonical.encode()).hexdigest()[:8]
    return f"trend-term-{h}"


def translate_chinese_canonicals(terms: list[dict]) -> list[dict]:
    """Use LLM to translate Chinese canonical names to English."""
    from llm_client import chat

    chinese_terms = [(i, t) for i, t in enumerate(terms) if _has_chinese(t.get("canonical", ""))]
    if not chinese_terms:
        return terms

    print(f"Found {len(chinese_terms)} Chinese canonical names to translate...")
    chinese_names = [t["canonical"] for _, t in chinese_terms]

    translate_prompt = f"""Translate these Chinese tech product/term names to concise, natural English equivalents.
Return a JSON object mapping each Chinese name to its English translation.

Chinese names:
{json.dumps(chinese_names, ensure_ascii=False)}

Rules:
- Keep English/technical terms intact (e.g. "GPT-5.6", "MCP", "API", "Kubernetes")
- Use natural English tech naming conventions
- Be concise (prefer 3-6 words)
- Preserve product names in original case

Return ONLY a JSON object: {{"chinese_name": "english translation", ...}}"""

    response = chat(
        "You are a translator specializing in Chinese→English tech terminology. Return only valid JSON.",
        translate_prompt,
    )
    response = response.strip()
    if response.startswith("```"):
        response = response.split("\n", 1)[1]
        if response.endswith("```"):
            response = response[:-3]
    translations = json.loads(response)

    for idx, term in chinese_terms:
        old_canonical = term["canonical"]
        english = translations.get(old_canonical, "").strip()
        if english and english != old_canonical:
            print(f"  [OK] {old_canonical} -> {english}")
            term["canonical_zh"] = old_canonical
            term["canonical"] = english
        else:
            print(f"  [SKIP] No translation for: {old_canonical}")

    return terms


def fix_ids_and_paths(terms: list[dict], dry_run: bool = False) -> list[dict]:
    """Update IDs and research_md_path for terms with Chinese IDs."""
    files_renamed = []

    for term in terms:
        old_id = term["id"]
        canonical = term.get("canonical", "")

        # Generate new English ID
        new_id = _make_slug_id(canonical)
        if new_id == old_id:
            continue

        old_slug = old_id.replace("trend-", "")
        new_slug = new_id.replace("trend-", "")
        print(f"  ID: {old_id} → {new_id}")

        if dry_run:
            continue

        term["id"] = new_id

        # Update research_md_path
        old_path = term.get("research_md_path", "")
        if old_path:
            term["research_md_path"] = f"content/trends/{new_slug}.md"

        # Rename content files if they exist
        for suffix in ["", "-en"]:
            old_file = CONTENT_DIR / f"{old_slug}{suffix}.md"
            new_file = CONTENT_DIR / f"{new_slug}{suffix}.md"
            if old_file.exists():
                old_file.rename(new_file)
                files_renamed.append((str(old_file), str(new_file)))
                print(f"    Renamed: {old_file.name} → {new_file.name}")

    if files_renamed:
        print(f"\nRenamed {len(files_renamed)} content files.")

    return terms


def main():
    dry_run = "--dry-run" in sys.argv

    print(f"{'[DRY RUN] ' if dry_run else ''}Loading {TREND_TERMS_PATH}...")
    with open(TREND_TERMS_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    terms = data.get("terms", [])
    chinese_count = sum(1 for t in terms if _has_chinese(t.get("canonical", "")))
    chinese_id_count = sum(1 for t in terms if _has_chinese(t.get("id", "")))

    print(f"Total terms: {len(terms)}")
    print(f"Chinese canonical: {chinese_count}")
    print(f"Chinese IDs: {chinese_id_count}")

    if chinese_count == 0 and chinese_id_count == 0:
        print("Nothing to fix!")
        return

    # Step 1: Translate Chinese canonicals
    print("\n--- Step 1: Translate Chinese canonicals ---")
    terms = translate_chinese_canonicals(terms)

    # Step 2: Fix IDs and rename content files
    print("\n--- Step 2: Fix IDs ---")
    terms = fix_ids_and_paths(terms, dry_run=dry_run)

    # Step 3: Deduplicate by ID (in case two terms got the same English ID)
    seen_ids = {}
    deduped = []
    for term in terms:
        tid = term["id"]
        if tid in seen_ids:
            print(f"  DEDUP: merging duplicate ID {tid}")
            existing = seen_ids[tid]
            # Merge: keep the one with more data
            existing["total_mentions"] += term.get("total_mentions", 0)
            for src in term.get("sources", []):
                if src not in existing["sources"]:
                    existing["sources"].append(src)
            existing["source_count"] = len(existing["sources"])
            if not existing.get("canonical_zh") and term.get("canonical_zh"):
                existing["canonical_zh"] = term["canonical_zh"]
            if not existing.get("summary_en") and term.get("summary_en"):
                existing["summary_en"] = term["summary_en"]
        else:
            seen_ids[tid] = term
            deduped.append(term)

    data["terms"] = deduped

    if dry_run:
        print(f"\n[DRY RUN] Would save {len(deduped)} terms (removed {len(terms) - len(deduped)} dupes)")
    else:
        print(f"\nSaving {len(deduped)} terms...")
        with open(TREND_TERMS_PATH, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print("Done!")


if __name__ == "__main__":
    main()
